language: node_js
node_js:
  - 12
before_install: true
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - "psql -c 'create database id;' -U postgres"
  - "psql -U postgres id < ./core/schema.sql"
script:
  - "cd core && npm ci && npm test && cd .."
  - "cd front && npm ci && npm run lint && npm run build && cd .."
